INFLUXDB_TOKEN: mgttvBQT_QTnKSWlumdhyJjbcuPXQn51S9EQlScfTilPz5RO7HAEOB1-oOw07h0tITlTx5jGCw6_o2YjRIvL6w==

INFLUXDB_BUCKET: gclog

INFLUXDB_ORG: sangmu.hhj@gmail.com

INFLUXDB_URL: https://us-east-1-1.aws.cloud2.influxdata.com